import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Pixelify_Sans } from "next/font/google";

import "./globals.scss";

const suisseIntl = localFont({
  src: [
    {
      path: "./fonts/SuisseIntlCondTrial-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SuisseIntlCondTrial-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-suisse",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-pixelify",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${suisseIntl.variable} ${inter.variable} ${pixelifySans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
